repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]

      - id: black
        name: black
        entry: python -m black .
        language: system
        types: [python]

      - id: autoflake
        name: autoflake
        entry: python -m autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: python -m isort --profile black .
        language: system
        types: [python]